export { default as CssSvg } from './logos/css.svgr'
export { default as GithubBlackSvg } from './logos/github-black.svgr'
export { default as GithubWhiteSvg } from './logos/github-white.svgr'
export { default as StorybookSvg } from './logos/storybook.svgr'
export { default as TailwindSvg } from './logos/tailwind.svgr'
export { default as TypescriptSvg } from './logos/typescript.svgr'
