/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CSS_PREFIX__BLUR = '--ds-blur-'

export const TOKENS__BLUR = {
  xs: { value: '1px' },
  sm: { value: '2px' },
  md: { value: '4px' },
  lg: { value: '6px' },
  subtle: { ref: 'blur.sm', value: '2px' },
  default: { ref: 'blur.md', value: '4px' },
} as const
