/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__COLOR = '.ds-color-'

export const CSS_PREFIX__COLOR = '--ds-color-'

export const TOKENS__COLOR = {
  white: { value: 'oklch(1 0 0)' },
  black: { value: 'oklch(0.2213 0.0065 314.68)' },
  'grey-1': { value: 'oklch(0.9884 0.0013 308)' },
  'grey-2': { value: 'oklch(0.9682 0.0017 308)' },
  'grey-3': { value: 'oklch(0.9474 0.0029 308)' },
  'grey-4': { value: 'oklch(0.9266 0.0042 308)' },
  'grey-5': { value: 'oklch(0.885 0.0058 308)' },
  'grey-6': { value: 'oklch(0.8432 0.0088 308)' },
  'grey-7': { value: 'oklch(0.7997 0.0103 308)' },
  'grey-8': { value: 'oklch(0.7548 0.0151 308)' },
  'grey-9': { value: 'oklch(0.711 0.0171 308)' },
  'grey-10': { value: 'oklch(0.666 0.0201 308)' },
  'grey-11': { value: 'oklch(0.6207 0.0223 308)' },
  'grey-12': { value: 'oklch(0.5683 0.0195 308)' },
  'grey-13': { value: 'oklch(0.516 0.0186 308)' },
  'grey-14': { value: 'oklch(0.461 0.0157 308)' },
  'grey-15': { value: 'oklch(0.4047 0.0142 308)' },
  'grey-16': { value: 'oklch(0.3771 0.0124 308)' },
  'grey-17': { value: 'oklch(0.346 0.011 308)' },
  'grey-18': { value: 'oklch(0.3171 0.0092 308)' },
  'grey-19': { value: 'oklch(0.2861 0.0099 308)' },
  'grey-20': { value: 'oklch(0.2558 0.0079 308)' },
  'purple-1': { value: 'oklch(0.9024 0.0604 306)' },
  'purple-2': { value: 'oklch(0.8268 0.1082 306)' },
  'purple-3': { value: 'oklch(0.7326 0.1697 306)' },
  'purple-4': { value: 'oklch(0.6324 0.2111 306)' },
  'purple-5': { value: 'oklch(0.5926 0.2335 306)' },
  'purple-6': { value: 'oklch(0.5575 0.2525 306)' },
  'purple-7': { value: 'oklch(0.4383 0.1983 306)' },
  'purple-8': { value: 'oklch(0.3442 0.1476 306)' },
  'blue-1': { value: 'oklch(0.9215 0.0348 260)' },
  'blue-2': { value: 'oklch(0.8434 0.0715 260)' },
  'blue-3': { value: 'oklch(0.7664 0.1113 260)' },
  'blue-4': { value: 'oklch(0.6923 0.1502 260)' },
  'blue-5': { value: 'oklch(0.6231 0.188 260)' },
  'blue-6': { value: 'oklch(0.5303 0.1572 260)' },
  'blue-7': { value: 'oklch(0.4333 0.1248 260)' },
  'blue-8': { value: 'oklch(0.2191 0.0494 260)' },
  'yellow-1': { value: 'oklch(0.9729 0.0693 103.19)' },
  'yellow-2': { value: 'oklch(0.9644 0.0817 101.79)' },
  'yellow-3': { value: 'oklch(0.9185 0.1426 98.22)' },
  'yellow-4': { value: 'oklch(0.8606 0.1731 91.94)' },
  'yellow-5': { value: 'oklch(0.6806 0.1423 75.83)' },
  'yellow-6': { value: 'oklch(0.5735 0.1211 72.88)' },
  'yellow-7': { value: 'oklch(0.5519 0.121 65.65)' },
  'yellow-8': { value: 'oklch(0.5082 0.1114 65.39)' },
  'red-1': { value: 'oklch(0.8845 0.0593 23)' },
  'red-2': { value: 'oklch(0.8077 0.1035 23)' },
  'red-3': { value: 'oklch(0.7305 0.1593 23)' },
  'red-4': { value: 'oklch(0.7106 0.1661 23)' },
  'red-5': { value: 'oklch(0.5919 0.2063 23)' },
  'red-6': { value: 'oklch(0.5696 0.2145 23)' },
  'red-7': { value: 'oklch(0.4991 0.1884 23)' },
  'red-8': { value: 'oklch(0.3958 0.1331 23)' },
  'green-1': { value: 'oklch(0.9624 0.0434 150)' },
  'green-2': { value: 'oklch(0.925 0.0806 150)' },
  'green-3': { value: 'oklch(0.8003 0.1821 150)' },
  'green-4': { value: 'oklch(0.7227 0.192 150)' },
  'green-5': { value: 'oklch(0.6271 0.1699 150)' },
  'green-6': { value: 'oklch(0.5475 0.1444 150)' },
  'green-7': { value: 'oklch(0.5267 0.1394 150)' },
  'green-8': { value: 'oklch(0.3925 0.0896 150)' },
  'black-alpha-1': { value: 'oklch(0.1068 0.0519 317 / 0.03)' },
  'black-alpha-2': { value: 'oklch(0.1068 0.0519 317 / 0.06)' },
  'black-alpha-3': { value: 'oklch(0.1068 0.0519 317 / 0.09)' },
  'black-alpha-4': { value: 'oklch(0.1068 0.0519 317 / 0.12)' },
  'black-alpha-5': { value: 'oklch(0.1068 0.0519 317 / 0.16)' },
  'black-alpha-6': { value: 'oklch(0.1068 0.0519 317 / 0.24)' },
  'black-alpha-7': { value: 'oklch(0.1068 0.0519 317 / 0.32)' },
  'black-alpha-8': { value: 'oklch(0.1068 0.0519 317 / 0.4)' },
  'black-alpha-9': { value: 'oklch(0.1068 0.0519 317 / 0.48)' },
  'black-alpha-10': { value: 'oklch(0.1068 0.0519 317 / 0.56)' },
  'white-alpha-1': { value: 'oklch(1 0 0 / 0.03)' },
  'white-alpha-2': { value: 'oklch(1 0 0 / 0.06)' },
  'white-alpha-3': { value: 'oklch(1 0 0 / 0.09)' },
  'white-alpha-4': { value: 'oklch(1 0 0 / 0.12)' },
  'white-alpha-5': { value: 'oklch(1 0 0 / 0.16)' },
  'white-alpha-6': { value: 'oklch(1 0 0 / 0.24)' },
  'white-alpha-7': { value: 'oklch(1 0 0 / 0.32)' },
  'white-alpha-8': { value: 'oklch(1 0 0 / 0.4)' },
  'white-alpha-9': { value: 'oklch(1 0 0 / 0.48)' },
  'white-alpha-10': { value: 'oklch(1 0 0 / 0.56)' },
  'bg-page': {
    ref: { light: '{color.grey-3}', dark: '{color.grey-19}' },
    value: { light: 'oklch(0.9474 0.0029 308)', dark: 'oklch(0.2861 0.0099 308)' },
  },
  'bg-sheet': {
    ref: { light: '{color.grey-2}', dark: '{color.grey-18}' },
    value: { light: 'oklch(0.9682 0.0017 308)', dark: 'oklch(0.3171 0.0092 308)' },
  },
  'bg-card': {
    ref: { light: '{color.grey-1}', dark: '{color.grey-17}' },
    value: { light: 'oklch(0.9884 0.0013 308)', dark: 'oklch(0.346 0.011 308)' },
  },
  'bg-popup': {
    ref: { light: '{color.white}', dark: '{color.grey-16}' },
    value: { light: 'oklch(1 0 0)', dark: 'oklch(0.3771 0.0124 308)' },
  },
  'bg-coding': {
    ref: { light: '{color.grey-5}', dark: '{color.grey-20}' },
    value: { light: 'oklch(0.885 0.0058 308)', dark: 'oklch(0.2558 0.0079 308)' },
  },
  'bg-field': {
    ref: { light: '{color.black-alpha-1}', dark: '{color.black-alpha-4}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.03)', dark: 'oklch(0.1068 0.0519 317 / 0.12)' },
  },
  'bg-skeleton': {
    ref: { light: '{color.black-alpha-3}', dark: '{color.white-alpha-5}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.09)', dark: 'oklch(1 0 0 / 0.16)' },
  },
  'bg-link': {
    ref: { light: '{color.black-alpha-2}', dark: '{color.black-alpha-5}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.06)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'bg-blockquote': {
    ref: { light: '{color.black-alpha-1}', dark: '{color.white-alpha-2}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.03)', dark: 'oklch(1 0 0 / 0.06)' },
  },
  'bg-highlight': {
    ref: { light: '{color.yellow-4}', dark: '{color.yellow-6}' },
    value: { light: 'oklch(0.8606 0.1731 91.94)', dark: 'oklch(0.5735 0.1211 72.88)' },
  },
  'border-active': {
    ref: { light: '{color.grey-12}', dark: '{color.grey-8}' },
    value: { light: 'oklch(0.5683 0.0195 308)', dark: 'oklch(0.7548 0.0151 308)' },
  },
  'border-hover': {
    ref: { light: '{color.grey-11}', dark: '{color.grey-12}' },
    value: { light: 'oklch(0.6207 0.0223 308)', dark: 'oklch(0.5683 0.0195 308)' },
  },
  'border-default': {
    ref: { light: '{color.grey-7}', dark: '{color.grey-14}' },
    value: { light: 'oklch(0.7997 0.0103 308)', dark: 'oklch(0.461 0.0157 308)' },
  },
  'border-subtle': {
    ref: { light: '{color.black-alpha-3}', dark: '{color.white-alpha-4}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.09)', dark: 'oklch(1 0 0 / 0.12)' },
  },
  'border-shadow': {
    ref: { light: '{color.grey-3}', dark: '{color.grey-20}' },
    value: { light: 'oklch(0.9474 0.0029 308)', dark: 'oklch(0.2558 0.0079 308)' },
  },
  'border-highlight': {
    ref: { light: '{color.yellow-3}', dark: '{color.yellow-4}' },
    value: { light: 'oklch(0.9185 0.1426 98.22)', dark: 'oklch(0.8606 0.1731 91.94)' },
  },
  'text-default': {
    ref: { light: '{color.black}', dark: '{color.white}' },
    value: { light: 'oklch(0.2213 0.0065 314.68)', dark: 'oklch(1 0 0)' },
  },
  'text-inverse': {
    ref: { light: '{color.white}', dark: '{color.black}' },
    value: { light: 'oklch(1 0 0)', dark: 'oklch(0.2213 0.0065 314.68)' },
  },
  'text-subtle': {
    ref: { light: '{color.grey-13}', dark: '{color.grey-8}' },
    value: { light: 'oklch(0.516 0.0186 308)', dark: 'oklch(0.7548 0.0151 308)' },
  },
  'text-placeholder': {
    ref: { light: '{color.grey-11}', dark: '{color.grey-11}' },
    value: { light: 'oklch(0.6207 0.0223 308)', dark: 'oklch(0.6207 0.0223 308)' },
  },
  'text-link': {
    ref: { light: '{color.purple-8}', dark: '{color.purple-1}' },
    value: { light: 'oklch(0.3442 0.1476 306)', dark: 'oklch(0.9024 0.0604 306)' },
  },
  'hover-text-default': {
    ref: { light: '{color.black-alpha-2}', dark: '{color.black-alpha-5}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.06)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'hover-text-pressed': {
    ref: { light: '{color.black-alpha-3}', dark: '{color.black-alpha-6}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.09)', dark: 'oklch(0.1068 0.0519 317 / 0.24)' },
  },
  'hover-button-default': {
    ref: { light: '{color.black-alpha-5}', dark: '{color.black-alpha-5}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.16)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'hover-button-pressed': {
    ref: { light: '{color.black-alpha-7}', dark: '{color.black-alpha-7}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.32)', dark: 'oklch(0.1068 0.0519 317 / 0.32)' },
  },
  'primary-button-bg': {
    ref: { light: '{color.purple-6}', dark: '{color.purple-5}' },
    value: { light: 'oklch(0.5575 0.2525 306)', dark: 'oklch(0.5926 0.2335 306)' },
  },
  'primary-button-text': {
    ref: { light: '{color.white}', dark: '{color.white}' },
    value: { light: 'oklch(1 0 0)', dark: 'oklch(1 0 0)' },
  },
  'primary-hover-default': {
    ref: { light: '{color.hover-button-default}', dark: '{color.hover-button-default}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.16)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'primary-hover-pressed': {
    ref: { light: '{color.hover-button-pressed}', dark: '{color.hover-button-pressed}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.32)', dark: 'oklch(0.1068 0.0519 317 / 0.32)' },
  },
  'primary-card-bg': {
    ref: { light: '{color.purple-1}', dark: '{color.purple-8}' },
    value: { light: 'oklch(0.9024 0.0604 306)', dark: 'oklch(0.3442 0.1476 306)' },
  },
  'primary-card-text': {
    ref: { light: '{color.purple-8}', dark: '{color.white}' },
    value: { light: 'oklch(0.3442 0.1476 306)', dark: 'oklch(1 0 0)' },
  },
  'primary-card-subtext': {
    ref: { light: '{color.purple-7}', dark: '{color.purple-3}' },
    value: { light: 'oklch(0.4383 0.1983 306)', dark: 'oklch(0.7326 0.1697 306)' },
  },
  'primary-page-text': {
    ref: { light: '{color.purple-6}', dark: '{color.purple-3}' },
    value: { light: 'oklch(0.5575 0.2525 306)', dark: 'oklch(0.7326 0.1697 306)' },
  },
  'secondary-button-bg': {
    ref: { light: '{color.yellow-3}', dark: '{color.yellow-2}' },
    value: { light: 'oklch(0.9185 0.1426 98.22)', dark: 'oklch(0.9644 0.0817 101.79)' },
  },
  'secondary-button-text': {
    ref: { light: '{color.yellow-8}', dark: '{color.yellow-7}' },
    value: { light: 'oklch(0.5082 0.1114 65.39)', dark: 'oklch(0.5519 0.121 65.65)' },
  },
  'secondary-hover-default': {
    ref: { light: '{color.black-alpha-4}', dark: '{color.hover-button-default}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.12)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'secondary-hover-pressed': {
    ref: { light: '{color.black-alpha-5}', dark: '{color.black-alpha-6}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.16)', dark: 'oklch(0.1068 0.0519 317 / 0.24)' },
  },
  'secondary-card-bg': {
    ref: { light: '{color.yellow-1}', dark: '{color.yellow-6}' },
    value: { light: 'oklch(0.9729 0.0693 103.19)', dark: 'oklch(0.5735 0.1211 72.88)' },
  },
  'secondary-card-text': {
    ref: { light: '{color.yellow-8}', dark: '{color.white}' },
    value: { light: 'oklch(0.5082 0.1114 65.39)', dark: 'oklch(1 0 0)' },
  },
  'secondary-card-subtext': {
    ref: { light: '{color.yellow-7}', dark: '{color.yellow-1}' },
    value: { light: 'oklch(0.5519 0.121 65.65)', dark: 'oklch(0.9729 0.0693 103.19)' },
  },
  'secondary-page-text': {
    ref: { light: '{color.yellow-7}', dark: '{color.yellow-2}' },
    value: { light: 'oklch(0.5519 0.121 65.65)', dark: 'oklch(0.9644 0.0817 101.79)' },
  },
  'danger-button-bg': {
    ref: { light: '{color.red-6}', dark: '{color.red-5}' },
    value: { light: 'oklch(0.5696 0.2145 23)', dark: 'oklch(0.5919 0.2063 23)' },
  },
  'danger-button-text': {
    ref: { light: '{color.white}', dark: '{color.white}' },
    value: { light: 'oklch(1 0 0)', dark: 'oklch(1 0 0)' },
  },
  'danger-hover-default': {
    ref: { light: '{color.hover-button-default}', dark: '{color.hover-button-default}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.16)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'danger-hover-pressed': {
    ref: { light: '{color.hover-button-pressed}', dark: '{color.hover-button-pressed}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.32)', dark: 'oklch(0.1068 0.0519 317 / 0.32)' },
  },
  'danger-card-bg': {
    ref: { light: '{color.red-1}', dark: '{color.red-8}' },
    value: { light: 'oklch(0.8845 0.0593 23)', dark: 'oklch(0.3958 0.1331 23)' },
  },
  'danger-card-text': {
    ref: { light: '{color.red-8}', dark: '{color.white}' },
    value: { light: 'oklch(0.3958 0.1331 23)', dark: 'oklch(1 0 0)' },
  },
  'danger-card-subtext': {
    ref: { light: '{color.red-7}', dark: '{color.red-2}' },
    value: { light: 'oklch(0.4991 0.1884 23)', dark: 'oklch(0.8077 0.1035 23)' },
  },
  'danger-page-text': {
    ref: { light: '{color.red-6}', dark: '{color.red-3}' },
    value: { light: 'oklch(0.5696 0.2145 23)', dark: 'oklch(0.7305 0.1593 23)' },
  },
  'success-button-bg': {
    ref: { light: '{color.green-6}', dark: '{color.green-6}' },
    value: { light: 'oklch(0.5475 0.1444 150)', dark: 'oklch(0.5475 0.1444 150)' },
  },
  'success-button-text': {
    ref: { light: '{color.white}', dark: '{color.white}' },
    value: { light: 'oklch(1 0 0)', dark: 'oklch(1 0 0)' },
  },
  'success-hover-default': {
    ref: { light: '{color.hover-button-default}', dark: '{color.hover-button-default}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.16)', dark: 'oklch(0.1068 0.0519 317 / 0.16)' },
  },
  'success-hover-pressed': {
    ref: { light: '{color.hover-button-pressed}', dark: '{color.hover-button-pressed}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.32)', dark: 'oklch(0.1068 0.0519 317 / 0.32)' },
  },
  'success-card-bg': {
    ref: { light: '{color.green-1}', dark: '{color.green-8}' },
    value: { light: 'oklch(0.9624 0.0434 150)', dark: 'oklch(0.3925 0.0896 150)' },
  },
  'success-card-text': {
    ref: { light: '{color.green-8}', dark: '{color.white}' },
    value: { light: 'oklch(0.3925 0.0896 150)', dark: 'oklch(1 0 0)' },
  },
  'success-card-subtext': {
    ref: { light: '{color.green-7}', dark: '{color.green-3}' },
    value: { light: 'oklch(0.5267 0.1394 150)', dark: 'oklch(0.8003 0.1821 150)' },
  },
  'success-page-text': {
    ref: { light: '{color.green-7}', dark: '{color.green-3}' },
    value: { light: 'oklch(0.5267 0.1394 150)', dark: 'oklch(0.8003 0.1821 150)' },
  },
  'modal-overlay-subtle': {
    ref: { light: '{color.black-alpha-7}', dark: '{color.black-alpha-6}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.32)', dark: 'oklch(0.1068 0.0519 317 / 0.24)' },
  },
  'modal-overlay-strong': {
    ref: { light: '{color.black-alpha-9}', dark: '{color.black-alpha-10}' },
    value: { light: 'oklch(0.1068 0.0519 317 / 0.48)', dark: 'oklch(0.1068 0.0519 317 / 0.56)' },
  },
  'chart-bar-default': {
    ref: { light: '{color.grey-12}', dark: '{color.grey-10}' },
    value: { light: 'oklch(0.5683 0.0195 308)', dark: 'oklch(0.666 0.0201 308)' },
  },
  'chart-bar-hover': {
    ref: { light: '{color.grey-14}', dark: '{color.grey-8}' },
    value: { light: 'oklch(0.461 0.0157 308)', dark: 'oklch(0.7548 0.0151 308)' },
  },
  'map-ocean': {
    ref: { light: '{color.blue-1}', dark: '{color.blue-8}' },
    value: { light: 'oklch(0.9215 0.0348 260)', dark: 'oklch(0.2191 0.0494 260)' },
  },
  'map-land': {
    ref: { light: '{color.grey-1}', dark: '{color.grey-18}' },
    value: { light: 'oklch(0.9884 0.0013 308)', dark: 'oklch(0.3171 0.0092 308)' },
  },
  'map-value-none': {
    ref: { light: '{color.purple-1}', dark: '{color.grey-14}' },
    value: { light: 'oklch(0.9024 0.0604 306)', dark: 'oklch(0.461 0.0157 308)' },
  },
  'map-value-min': {
    ref: { light: '{color.purple-2}', dark: '{color.purple-7}' },
    value: { light: 'oklch(0.8268 0.1082 306)', dark: 'oklch(0.4383 0.1983 306)' },
  },
  'map-value-max': {
    ref: { light: '{color.purple-8}', dark: '{color.purple-1}' },
    value: { light: 'oklch(0.3442 0.1476 306)', dark: 'oklch(0.9024 0.0604 306)' },
  },
} as const
