/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__FONT_WEIGHT = '.ds-font-weight-'

export const CSS_PREFIX__FONT_WEIGHT = '--ds-font-weight-'

export const TOKENS__FONT_WEIGHT = {
  xs: { value: 300 },
  sm: { value: 400 },
  md: { value: 500 },
  lg: { value: 600 },
  xl: { value: 700 },
} as const
