/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__FONT_FAMILY = '.ds-font-family-'

export const CSS_PREFIX__FONT_FAMILY = '--ds-font-family-'

export const TOKENS__FONT_FAMILY = {
  sans: { value: "'Geist', sans-serif" },
  mono: { value: "'Geist Mono', monospace" },
} as const
