/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__MOTION = 'ds-motion-'

export const CSS_PREFIX__MOTION = '--ds-motion-'

export const TOKENS__MOTION = {
  'duration-xs': { value: '0.1s' },
  'duration-sm': { value: '0.2s' },
  'duration-md': { value: '0.4s' },
  'duration-lg': { value: '0.6s' },
  'duration-xl': { value: '1.0s' },
} as const
