/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CSS_PREFIX__RADIUS = '--ds-radius-'

export const TOKENS__RADIUS = {
  xs: { value: '4px' },
  sm: { value: '6px' },
  md: { value: '8px' },
  lg: { value: '12px' },
  xl: { value: '16px' },
  max: { value: '99px' },
  full: { value: '100%' },
} as const
