/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__SHADOW = 'ds-shadow-'

export const CSS_PREFIX__SHADOW = '--ds-shadow-'

export const TOKENS__SHADOW = {
  xs: {
    ref: {
      light: ['0 0 4px -2px {color.black-alpha-2}', '0 2px 3px -1px {color.black-alpha-4}'],
      dark: ['0 0 4px -2px {color.black-alpha-3}', '0 2px 3px -1px {color.black-alpha-7}'],
    },
    value: {
      light: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.06)', '0 2px 3px -1px oklch(0.1068 0.0519 317 / 0.12)'],
      dark: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.09)', '0 2px 3px -1px oklch(0.1068 0.0519 317 / 0.32)'],
    },
  },
  sm: {
    ref: {
      light: ['0 0 4px -2px {color.black-alpha-2}', '0 3px 5px -1px {color.black-alpha-4}'],
      dark: ['0 0 4px -2px {color.black-alpha-3}', '0 3px 5px -1px {color.black-alpha-7}'],
    },
    value: {
      light: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.06)', '0 3px 5px -1px oklch(0.1068 0.0519 317 / 0.12)'],
      dark: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.09)', '0 3px 5px -1px oklch(0.1068 0.0519 317 / 0.32)'],
    },
  },
  md: {
    ref: {
      light: ['0 0 4px -2px {color.black-alpha-2}', '0 4px 6px -1px {color.black-alpha-4}'],
      dark: ['0 0 4px -2px {color.black-alpha-3}', '0 4px 6px -1px {color.black-alpha-7}'],
    },
    value: {
      light: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.06)', '0 4px 6px -1px oklch(0.1068 0.0519 317 / 0.12)'],
      dark: ['0 0 4px -2px oklch(0.1068 0.0519 317 / 0.09)', '0 4px 6px -1px oklch(0.1068 0.0519 317 / 0.32)'],
    },
  },
  'inset-xs': {
    ref: {
      light: ['inset 0 1px 1px 0 {color.black-alpha-1}', 'inset 0 0 2px 1px {color.black-alpha-1}'],
      dark: ['inset 0 1px 1px 0 {color.black-alpha-2}', 'inset 0 0 2px 1px {color.black-alpha-2}'],
    },
    value: {
      light: ['inset 0 1px 1px 0 oklch(0.1068 0.0519 317 / 0.03)', 'inset 0 0 2px 1px oklch(0.1068 0.0519 317 / 0.03)'],
      dark: ['inset 0 1px 1px 0 oklch(0.1068 0.0519 317 / 0.06)', 'inset 0 0 2px 1px oklch(0.1068 0.0519 317 / 0.06)'],
    },
  },
  'inset-sm': {
    ref: {
      light: ['inset 0 2px 3px 1px {color.black-alpha-2}', 'inset 0 0 2px 1px {color.black-alpha-1}'],
      dark: ['inset 0 2px 3px 1px {color.black-alpha-3}', 'inset 0 0 2px 1px {color.black-alpha-2}'],
    },
    value: {
      light: [
        'inset 0 2px 3px 1px oklch(0.1068 0.0519 317 / 0.06)',
        'inset 0 0 2px 1px oklch(0.1068 0.0519 317 / 0.03)',
      ],
      dark: [
        'inset 0 2px 3px 1px oklch(0.1068 0.0519 317 / 0.09)',
        'inset 0 0 2px 1px oklch(0.1068 0.0519 317 / 0.06)',
      ],
    },
  },
  'below-sm': {
    ref: { light: '0 6px 6px -6px {color.black-alpha-5}', dark: '0 6px 6px -6px {color.black-alpha-10}' },
    value: {
      light: '0 6px 6px -6px oklch(0.1068 0.0519 317 / 0.16)',
      dark: '0 6px 6px -6px oklch(0.1068 0.0519 317 / 0.56)',
    },
  },
} as const
