/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__SURFACE = '.ds-surface-'

export const CSS_PREFIX__SURFACE = '--ds-surface-'

export const TOKENS__SURFACE = {
  page: {
    type: 'composite',
    ref: { backgroundColor: 'color.bg-page' },
    value: { backgroundColor: { light: 'oklch(0.9474 0.0029 308)', dark: 'oklch(0.2861 0.0099 308)' } },
  },
  sheet: {
    type: 'composite',
    ref: { backgroundColor: 'color.bg-sheet', borderRadius: 'radius.md', boxShadow: 'shadow.xs' },
    value: {
      backgroundColor: { light: 'oklch(0.9682 0.0017 308)', dark: 'oklch(0.3171 0.0092 308)' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  card: {
    type: 'composite',
    ref: {
      backgroundColor: { light: 'color.bg-card', dark: 'color.bg-card' },
      borderRadius: 'radius.md',
      boxShadow: 'shadow.xs',
    },
    value: {
      backgroundColor: { light: '{color.bg-card}', dark: '{color.bg-card}' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  popup: {
    type: 'composite',
    ref: { backgroundColor: 'color.bg-popup', borderRadius: 'radius.sm', boxShadow: 'shadow.xs' },
    value: {
      backgroundColor: { light: 'oklch(1 0 0)', dark: 'oklch(0.3771 0.0124 308)' },
      borderRadius: '6px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
} as const
