/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__SURFACE = '.ds-surface-'

export const CSS_PREFIX__SURFACE = '--ds-surface-'

export const TOKENS__SURFACE = {
  page: {
    type: 'composite',
    ref: {},
    value: {
      backgroundImage: {
        light: [
          'radial-gradient(circle, oklch(0.7548 0.0151 308) 1px, transparent 1px)',
          'linear-gradient(120deg, oklch(0.9215 0.0348 260), oklch(0.9474 0.0029 308), oklch(0.9474 0.0029 308))',
        ],
        dark: [
          'radial-gradient(circle, oklch(0.461 0.0157 308) 1px, transparent 1px)',
          'linear-gradient(120deg, oklch(0.2191 0.0494 260), oklch(0.2861 0.0099 308), oklch(0.2861 0.0099 308))',
        ],
      },
      backgroundSize: '12px 12px, cover',
    },
  },
  sheet: {
    type: 'composite',
    ref: { backgroundColor: '{color.bg-sheet}', borderRadius: '{radius.md}', boxShadow: '{shadow.xs}' },
    value: {
      backgroundColor: { light: 'oklch(0.9682 0.0017 308)', dark: 'oklch(0.3171 0.0092 308)' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  card: {
    type: 'composite',
    ref: {
      backgroundColor: { light: '{color.bg-card}', dark: '{color.bg-card}' },
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      backgroundColor: { light: 'oklch(0.9884 0.0013 308)', dark: 'oklch(0.346 0.011 308)' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  popup: {
    type: 'composite',
    ref: { backgroundColor: '{color.bg-popup}', borderRadius: '{radius.sm}', boxShadow: '{shadow.sm}' },
    value: {
      backgroundColor: { light: 'oklch(1 0 0)', dark: 'oklch(0.3771 0.0124 308)' },
      borderRadius: '6px',
      boxShadow: {
        light: ['0 1px 3px 0 rgb(0 0 0 / 0.15)', '0 1px 2px -1px rgb(0 0 0 / 0.15)'],
        dark: ['0 1px 3px 0 rgb(0 0 0 / 0.4)', '0 1px 2px -1px rgb(0 0 0 / 0.4)'],
      },
    },
  },
} as const
