/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CLASS_PREFIX__SURFACE = 'ds-surface-'

export const CSS_PREFIX__SURFACE = '--ds-surface-'

export const TOKENS__SURFACE = {
  page: {
    type: 'composite',
    ref: {
      backgroundColor: '{color.bg-page}',
      backgroundImage: {
        light: [
          'radial-gradient(circle, {color.black-alpha-2} 0.8px, transparent 0.8px)',
          'linear-gradient(100deg, {color.blue-1}, {color.bg-page} 20% 80%, {color.yellow-1})',
        ],
        dark: [
          'radial-gradient(circle, {color.white-alpha-2} 0.8px, transparent 0.8px)',
          'linear-gradient(100deg, {color.blue-8}, {color.grey-19} 20% 80%, {color.yellow-8})',
        ],
      },
    },
    value: {
      backgroundColor: { light: 'oklch(0.9474 0.0029 308)', dark: 'oklch(0.2861 0.0099 308)' },
      backgroundImage: {
        light: [
          'radial-gradient(circle, oklch(0.1068 0.0519 317 / 0.06) 0.8px, transparent 0.8px)',
          'linear-gradient(100deg, oklch(0.9215 0.0348 260), oklch(0.9474 0.0029 308) 20% 80%, oklch(0.9729 0.0693 103.19))',
        ],
        dark: [
          'radial-gradient(circle, oklch(1 0 0 / 0.06) 0.8px, transparent 0.8px)',
          'linear-gradient(100deg, oklch(0.2191 0.0494 260), oklch(0.2861 0.0099 308) 20% 80%, oklch(0.5082 0.1114 65.39))',
        ],
      },
      backgroundSize: '12px 12px, cover',
    },
  },
  sheet: {
    type: 'composite',
    ref: {
      backgroundColor: '{color.bg-sheet}',
      border: '1px solid {color.bg-card}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      backgroundColor: { light: 'oklch(0.9682 0.0017 308)', dark: 'oklch(0.3171 0.0092 308)' },
      border: { light: '1px solid oklch(0.9884 0.0013 308)', dark: '1px solid oklch(0.346 0.011 308)' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  card: {
    type: 'composite',
    ref: {
      backgroundColor: '{color.bg-card}',
      border: '1px solid {color.bg-card}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      backgroundColor: { light: 'oklch(0.9884 0.0013 308)', dark: 'oklch(0.346 0.011 308)' },
      border: { light: '1px solid oklch(0.9884 0.0013 308)', dark: '1px solid oklch(0.346 0.011 308)' },
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  'card-hovered': {
    type: 'composite',
    ref: {
      backgroundColor: '{color.yellow-1}',
      border: '2px solid {color.yellow-3}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      backgroundColor: 'oklch(0.9729 0.0693 103.19)',
      border: '2px solid oklch(0.9185 0.1426 98.22)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  popup: {
    type: 'composite',
    ref: { backgroundColor: '{color.bg-popup}', borderRadius: '{radius.sm}', boxShadow: '{shadow.sm}' },
    value: {
      backgroundColor: { light: 'oklch(1 0 0)', dark: 'oklch(0.3771 0.0124 308)' },
      borderRadius: '6px',
      boxShadow: {
        light: ['0 1px 3px 0 rgb(0 0 0 / 0.15)', '0 1px 2px -1px rgb(0 0 0 / 0.15)'],
        dark: ['0 1px 3px 0 rgb(0 0 0 / 0.4)', '0 1px 2px -1px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-primary': {
    type: 'composite',
    ref: {
      color: '{color.white}',
      backgroundColor: '{color.blue-6}',
      border: '1px solid {color.blue-6}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      color: 'oklch(1 0 0)',
      backgroundColor: 'oklch(0.5303 0.1572 260)',
      border: '1px solid oklch(0.5303 0.1572 260)',
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  'button-primary-hovered': {
    type: 'composite',
    ref: {
      color: '{color.white}',
      backgroundColor: '{color.blue-4}',
      border: '2px solid {color.blue-5}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: 'oklch(1 0 0)',
      backgroundColor: 'oklch(0.6923 0.1502 260)',
      border: '2px solid oklch(0.6231 0.188 260)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-secondary': {
    type: 'composite',
    ref: {
      color: '{color.blue-6}',
      border: '1px solid {color.blue-6}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      color: 'oklch(0.5303 0.1572 260)',
      border: '1px solid oklch(0.5303 0.1572 260)',
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  'button-secondary-hovered': {
    type: 'composite',
    ref: {
      color: '{color.blue-6}',
      backgroundColor: '{color.blue-1}',
      border: '2px solid {color.blue-5}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: 'oklch(0.5303 0.1572 260)',
      backgroundColor: 'oklch(0.9215 0.0348 260)',
      border: '2px solid oklch(0.6231 0.188 260)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-tertiary': {
    type: 'composite',
    ref: { color: '{color.text-default}' },
    value: { color: { light: 'oklch(0.2213 0.0065 314.68)', dark: 'oklch(1 0 0)' } },
  },
  'button-tertiary-hovered': {
    type: 'composite',
    ref: {
      color: '{color.text-default}',
      backgroundColor: '{color.yellow-1}',
      border: '2px solid {color.yellow-3}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: { light: 'oklch(0.2213 0.0065 314.68)', dark: 'oklch(1 0 0)' },
      backgroundColor: 'oklch(0.9729 0.0693 103.19)',
      border: '2px solid oklch(0.9185 0.1426 98.22)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-optional': {
    type: 'composite',
    ref: { color: '{color.text-subtle}' },
    value: { color: { light: 'oklch(0.516 0.0186 308)', dark: 'oklch(0.7548 0.0151 308)' } },
  },
  'button-optional-hovered': {
    type: 'composite',
    ref: {
      color: '{color.text-default}',
      backgroundColor: '{color.yellow-1}',
      border: '2px solid {color.yellow-3}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: { light: 'oklch(0.2213 0.0065 314.68)', dark: 'oklch(1 0 0)' },
      backgroundColor: 'oklch(0.9729 0.0693 103.19)',
      border: '2px solid oklch(0.9185 0.1426 98.22)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-danger': {
    type: 'composite',
    ref: {
      color: '{color.white}',
      backgroundColor: '{color.red-6}',
      border: '1px solid {color.red-6}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.xs}',
    },
    value: {
      color: 'oklch(1 0 0)',
      backgroundColor: 'oklch(0.5696 0.2145 23)',
      border: '1px solid oklch(0.5696 0.2145 23)',
      borderRadius: '8px',
      boxShadow: { light: '0 1px 2px 0 rgb(0 0 0 / 0.15)', dark: '0 1px 2px 0 rgb(0 0 0 / 0.4)' },
    },
  },
  'button-danger-hovered': {
    type: 'composite',
    ref: {
      color: '{color.white}',
      backgroundColor: '{color.red-4}',
      border: '2px solid {color.red-5}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: 'oklch(1 0 0)',
      backgroundColor: 'oklch(0.7106 0.1661 23)',
      border: '2px solid oklch(0.5919 0.2063 23)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
  'button-caution': { type: 'composite', ref: { color: '{color.red-6}' }, value: { color: 'oklch(0.5696 0.2145 23)' } },
  'button-caution-hovered': {
    type: 'composite',
    ref: {
      color: '{color.red-6}',
      backgroundColor: '{color.red-1}',
      borderRadius: '{radius.md}',
      boxShadow: '{shadow.md}',
    },
    value: {
      color: 'oklch(0.5696 0.2145 23)',
      backgroundColor: 'oklch(0.8845 0.0593 23)',
      borderRadius: '8px',
      boxShadow: {
        light: ['0 4px 6px -1px rgb(0 0 0 / 0.15)', '0 2px 4px -2px rgb(0 0 0 / 0.15)'],
        dark: ['0 4px 6px -1px rgb(0 0 0 / 0.4)', '0 2px 4px -2px rgb(0 0 0 / 0.4)'],
      },
    },
  },
} as const
