/* eslint-disable max-lines */
/**
 * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary
 */

export const CSS_PREFIX__Z_INDEX = '--ds-z-index-'

export const TOKENS__Z_INDEX = {
  lv1: { value: 1000 },
  lv2: { value: 2000 },
  lv3: { value: 3000 },
  lv4: { value: 4000 },
  lv5: { value: 5000 },
  lv6: { value: 6000 },
  lv7: { value: 7000 },
  lv8: { value: 8000 },
  lv9: { value: 9000 },
  sticky: { ref: 'z-index.lv1', value: 1000 },
  navbar: { ref: 'z-index.lv2', value: 2000 },
  modal: { ref: 'z-index.lv3', value: 3000 },
  popup: { ref: 'z-index.lv4', value: 4000 },
  dropdown: { ref: 'z-index.lv5', value: 5000 },
  toast: { ref: 'z-index.lv6', value: 6000 },
  tooltip: { ref: 'z-index.lv9', value: 9000 },
} as const
