import prettier from 'prettier'
import StyleDictionary, { type TransformedToken } from 'style-dictionary'
import { type FormatFnArguments } from 'style-dictionary/types'
import { formattedVariables } from 'style-dictionary/utils'

type TokenColorMode = '$light' | '$dark'

const FORMAT_NAME_CSS = 'css/ds-format'
const FORMAT_NAME_TS = 'ts/ds-format'
const NOTICE = [
  '/* eslint-disable max-lines */',
  '/**',
  ' * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary',
  ' */',
  '', //
].join('\n')

const prettierConfig = await prettier.resolveConfig(process.cwd() + '/package.json')

const stripNamespace = (ref: string) => ref.slice(1, -1).split('.').slice(1).join('.')
const hasColorMode = (value: unknown) => typeof value === 'object' && value && '$light' in value && '$dark' in value

StyleDictionary.registerFormat({
  name: FORMAT_NAME_CSS,
  format: async ({ dictionary, options }: FormatFnArguments) => {
    const formatOptions = {
      usesDtcg: true,
      format: 'css',
      outputReferences: options.outputReferences,
    }
    const mapTokens = (tokens: TransformedToken[], mode: TokenColorMode) => {
      return tokens
        .filter((token) => mode === '$light' || hasColorMode(token.$value))
        .map((token) => {
          const modeValue = hasColorMode(token.$value) ? token.$value[mode] : token.$value
          return {
            ...token,
            $value: modeValue,
            original: {
              ...token.original,
              $value: hasColorMode(token.original.$value) ? token.original.$value[mode] : token.original.$value,
            },
          }
        })
    }
    const getVars = (mode: TokenColorMode) => {
      const allTokens = mapTokens(dictionary.allTokens, mode)
      return formattedVariables({ dictionary: { ...dictionary, allTokens }, ...formatOptions })
    }
    const darkVars = getVars('$dark')
    const lightSelector = darkVars ? `,\n[data-color-mode='light']` : ''
    const lightOutput = `:root,\n:host${lightSelector} {\n${getVars('$light')}\n}\n`
    const darkOutput = darkVars ? `\n[data-color-mode='dark'] {\n${darkVars}\n}\n` : ''
    const output = NOTICE + lightOutput + darkOutput

    return await prettier.format(output, { ...prettierConfig, parser: 'css' })
  },
})

StyleDictionary.registerFormat({
  name: FORMAT_NAME_TS,
  format: async ({ dictionary }: FormatFnArguments) => {
    const toRef = (value: unknown) => {
      return typeof value === 'string' && value.startsWith('{') && value.endsWith('}') ? stripNamespace(value) : null
    }
    const buildObject = (tokens: typeof dictionary.allTokens) => {
      const result: Record<string, unknown> = {}

      for (const token of tokens) {
        const keys = token.path.slice(1)
        let current = result

        for (let i = 0; i < keys.length - 1; i++) {
          current[keys[i]] ??= {}
          current = current[keys[i]] as Record<string, unknown>
        }

        const leaf = keys[keys.length - 1]
        const value = token.original?.$value

        if (hasColorMode(value)) {
          const lightRef = toRef(value.$light)
          const darkRef = toRef(value.$dark)
          current[leaf] =
            lightRef && darkRef
              ? { ref: { light: lightRef, dark: darkRef } }
              : { value: { light: lightRef ?? value.$light, dark: darkRef ?? value.$dark } }
        } else {
          const ref = toRef(value)
          current[leaf] = ref ? { ref } : { value: token.$value }
        }
      }

      return result
    }
    const namespace = dictionary.allTokens[0]?.path[0] ?? 'unknown'
    const varName = namespace.toUpperCase().replaceAll('-', '_')
    const obj = buildObject(dictionary.allTokens)
    const json = JSON.stringify(obj, null, 2).replaceAll('\n', '')
    const output =
      NOTICE +
      `export const CSS_PREFIX__${varName} = '--ds-${namespace}-'\n\n` +
      `export const TOKENS__${varName} = ${json} as const\n`

    return await prettier.format(output, { ...prettierConfig, parser: 'typescript' })
  },
})

export { FORMAT_NAME_CSS, FORMAT_NAME_TS }
