import StyleDictionary from 'style-dictionary'
import { type FormatFnArguments } from 'style-dictionary/types'
import { formattedVariables } from 'style-dictionary/utils'
import { type DesignTokenGroup } from '../../src/styles/tokens/index.ts'

const FORMAT_NAME = 'css/ds-format'

const formatTokens = (groups: Record<string, DesignTokenGroup>) => {
  return Object.fromEntries(
    Object.entries(groups).map(([namespace, group]) => {
      const formatRef = (value: string) => `{${namespace}.${value}}`
      return [
        namespace,
        Object.fromEntries(
          Object.entries(group).map(([key, token]) => {
            if (typeof token.$value === 'object') {
              return [key, { $value: token.$value.light, $extensions: { dark: token.$value.dark } }]
            }
            if (typeof token.$ref === 'object') {
              return [key, { $value: formatRef(token.$ref.light), $extensions: { dark: formatRef(token.$ref.dark) } }]
            }
            return [key, { $value: token.$ref ? formatRef(token.$ref) : token.$value }]
          }),
        ),
      ]
    }),
  )
}

StyleDictionary.registerFormat({
  name: FORMAT_NAME,
  format: ({ dictionary, options }: FormatFnArguments) => {
    const formatOptions = {
      usesDtcg: true,
      format: 'css',
      outputReferences: options.outputReferences,
    }
    const warning = [
      '/**',
      ' * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary',
      ' */',
      '', //
    ].join('\n')

    // Light
    const lightVars = formattedVariables({ dictionary, ...formatOptions })
    const lightOutput = `:root,\n:host {\n${lightVars}\n}\n`

    // Dark
    const darkDictionary = {
      ...dictionary,
      allTokens: dictionary.allTokens
        .filter((token) => token.$extensions?.dark)
        .map((token) => {
          return {
            ...token,
            $value: token.$extensions.dark,
            original: { ...token.original, $value: token.original.$extensions.dark },
          }
        }),
    }
    const darkVars = formattedVariables({ dictionary: darkDictionary, ...formatOptions })
    const darkOutput = darkVars ? `\n[data-color-theme='dark'] {\n${darkVars}\n}\n` : ''

    return warning + lightOutput + darkOutput
  },
})

export { FORMAT_NAME, formatTokens }
