import prettier from 'prettier'
import { type TokenColoredValue } from './schema.ts'

export const NOTICE = [
  '/* eslint-disable max-lines */',
  '/**',
  ' * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary',
  ' */',
  '', //
].join('\n')

export const prettierConfig = await prettier.resolveConfig(process.cwd() + '/package.json')

export const isColoredValue = (value: unknown): value is TokenColoredValue => {
  return Boolean(typeof value === 'object' && value && '$light' in value && '$dark' in value)
}

export const isColoredArray = (array: unknown): array is TokenColoredValue[] => {
  return Boolean(Array.isArray(array) && array.some((value) => isColoredValue(value)))
}
