import prettier from 'prettier'

export type TokenColorMode = '$light' | '$dark'

export const NOTICE = [
  '/* eslint-disable max-lines */',
  '/**',
  ' * ⚠️ DO NOT EDIT — This file is auto-generated by Style Dictionary',
  ' */',
  '', //
].join('\n')

export const prettierConfig = await prettier.resolveConfig(process.cwd() + '/package.json')

export const hasColorMode = (value: unknown) => {
  return typeof value === 'object' && value && '$light' in value && '$dark' in value
}
