import { type Metadata } from 'next'
import { AppLogo } from '../components/app-logo/app-logo.tsx'
import { AppNav } from '../components/app-nav/app-nav.tsx'
import { NavMenu } from '../components/nav-menu/nav-menu.tsx'
import '../env.server.ts'
import { DEFAULT_LOCALE } from '../i18n/i18n-config.ts'
import '../styling/index.ts'
import { Providers } from './_setup/providers.tsx'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: ReactProps) {
	return (
		<html lang={DEFAULT_LOCALE}>
			<body className="h-screen">
				<Providers>
					<AppNav appLogo={AppLogo} navMenu={NavMenu}>
						<div className="px-xs-8 pt-xs-7 pb-sm-5 relative flex h-full w-full">{children}</div>
					</AppNav>
				</Providers>
			</body>
		</html>
	)
}
