import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { AppNav } from '../components/app-nav/app-nav.tsx'
import '../env.ts'
import { DEFAULT_LOCALE } from '../i18n/i18n-config.ts'
import '../styling/index.ts'
import { NavMenu } from './_layout/nav-menu.tsx'
import { Providers } from './_layout/providers.tsx'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang={DEFAULT_LOCALE}>
			<body className={cx('antialiased', geistSans.variable, geistMono.variable)}>
				<Providers>
					<AppNav navContentFn={NavMenu}>{children}</AppNav>
				</Providers>
			</body>
		</html>
	)
}
