name: GitHub Pages

on:
  # GitHub Pages require environment permissions per branch
  # On merge, GitHub Actions can only run from source branches
  # The only option is to run the workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint DS project
        run: cd ds && pnpm run code--lint

      - name: Lint app project
        run: cd app && pnpm run code--lint

  test:
    name: Testing
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: (DS) Install Playwright browsers
        run: cd ds && pnpm exec playwright install chromium

      - name: (App) Install Playwright browsers
        run: cd app && pnpm exec playwright install chromium firefox webkit --with-deps

      - name: (DS) Test Storybook
        run: cd ds && pnpm run docs--test || pnpm run docs--test # First attempt fails due to Vitest/Storybook issues

      - name: (App) Test Storybook
        run: cd app && pnpm run sb--test || pnpm run sb--test # First attempt fails due to Vitest/Storybook issues

      - name: (App) Test e2e locally
        run: cd app && pnpm run app--build && pnpm run app--test--ci-local
        env:
          USE_LOCAL: "true"

      - name: Upload e2e report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out-e2e-local
          path: app/out-e2e-local
          retention-days: 1

  build:
    name: Building
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build DS Storybook
        run: cd ds && pnpm run docs--build

      - name: Build Next.js app
        run: cd app && pnpm run app--build

      - name: Build app Storybook
        run: cd app && pnpm run sb--build

      - name: Download e2e report
        uses: actions/download-artifact@v4
        with:
          name: out-e2e-local
          path: app/out-e2e-local

      - name: Prepare deployment directory
        run: |
          mkdir -p _deploy
          cp -r app/out-app/* _deploy/
          mkdir -p _deploy/storybook
          cp -r app/out-sb/* _deploy/storybook/
          mkdir -p _deploy/e2e-tests
          cp -r app/out-e2e-local/* _deploy/e2e-tests/
          mkdir -p _deploy/design-system
          cp -r ds/out-docs/* _deploy/design-system/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_deploy"

  deploy:
    name: Deploying
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  validate:
    name: Validating
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Install Playwright browsers
        run: cd app && pnpm exec playwright install chromium --with-deps

      - name: Test e2e live
        run: cd app && pnpm run app--test--ci-live
