name: PR Status Checks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Lint DS project
        run: cd ds && pnpm run code--lint

      - name: Lint app project
        run: cd app && pnpm run code--lint

  test:
    name: Testing
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: (DS) Install Playwright browsers
        run: cd ds && pnpm exec playwright install chromium

      - name: (App) Install Playwright browsers
        run: cd app && pnpm exec playwright install chromium firefox webkit --with-deps

      - name: (DS) Test Storybook
        run: cd ds && pnpm run docs--test || pnpm run docs--test # First attempt fails due to Vitest/Storybook issues

      - name: (App) Test Storybook
        run: cd app && pnpm run sb--test || pnpm run sb--test # First attempt fails due to Vitest/Storybook issues

      - name: (App) Test e2e locally
        run: cd app && pnpm run app--build && pnpm run app--test--ci-local
        env:
          USE_LOCAL: "true"
